.docker_stages: &docker_stages
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:19.03.5-dind
  before_script:
    - docker info
    - docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  after_script:
    - docker logout ${CI_REGISTRY}

# push strategy comes from: https://blog.callr.tech/building-docker-images-with-gitlab-ci-best-practices/
stages:
  - build
  - push_current
  - deploy

Production Build:
  <<: *docker_stages
  stage: build
  only:
    - production
    - development
  script:
    - docker pull ${CI_REGISTRY_IMAGE}:production || true
    - >
      docker build
      --pull
      --build-arg VCS_REF=${CI_COMMIT_SHA}
      --build-arg VCS_URL=${CI_PROJECT_URL}
      --cache-from ${CI_REGISTRY_IMAGE}:production
      --tag ${CI_REGISTRY_IMAGE}:git-${CI_COMMIT_SHORT_SHA}
      --file cluster.dockerfile
      .
    - docker push ${CI_REGISTRY_IMAGE}:git-${CI_COMMIT_SHORT_SHA}

Lab Build:
  <<: *docker_stages
  stage: build
  tags:
    - busterk8s
  only:
    - labdev
  script:
    - docker pull ${CI_REGISTRY_IMAGE}:labdev || true
    - >
      docker build
      --pull
      --build-arg VCS_REF=${CI_COMMIT_SHA}
      --build-arg VCS_URL=${CI_PROJECT_URL}
      --cache-from ${CI_REGISTRY_IMAGE}:labdev
      --tag ${CI_REGISTRY_IMAGE}:git-${CI_COMMIT_SHORT_SHA}
      --file cluster.dockerfile
      .
    - docker push ${CI_REGISTRY_IMAGE}:git-${CI_COMMIT_SHORT_SHA}

Push current:
  <<: *docker_stages
  variables:
    GIT_STRATEGY: none
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  stage: push_current
  only:
    - production
    - development
    - labdev
  script:
    - docker pull ${CI_REGISTRY_IMAGE}:git-${CI_COMMIT_SHORT_SHA}
    - docker tag ${CI_REGISTRY_IMAGE}:git-${CI_COMMIT_SHORT_SHA} ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}

Deployment:
  stage: deploy
  only:
    - development
    - production
    - labdev
  image: registry.gitlab.com/outfielding/ansible-deployer:latest
  before_script:
    - ansible --version
  script:
    - cd deployment
    - export vars_file_var="ANSIBLE_${CI_COMMIT_REF_NAME^^}_VARS"
    - export ANSIBLE_DEPLOYMENT_VARS=${!vars_file_var}
    - ansible-playbook deploy.yml
