image: docker:stable

stages:
  - build_and_push

services:
  - docker:18.09.7-dind

before_script:
  - docker info

Build:
  stage: build_and_push
  only:
    - production
    - development
  before_script:
    - docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  script:
    - docker pull ${CI_COMMIT_REF_NAME}/${CI_REGISTRY_IMAGE}:latest || true 
    - >
      docker build
      --pull
      --build-arg VCS_REF=${CI_COMMIT_SHA}
      --build-arg VCS_URL=${CI_PROJECT_URL}
      --cache-from ${CI_COMMIT_REF_NAME}/${CI_REGISTRY_IMAGE}:latest
      --tag ${CI_COMMIT_REF_NAME}/${CI_REGISTRY_IMAGE}:latest
      --file cluster.dockerfile
      .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  after_script:
    - docker logout ${CI_REGISTRY}
