apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: registry.gitlab.com/rambleon/busterleague
  newName: registry.gitlab.com/rambleon/busterleague
  newTag: latest
