---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ kube_resource_name }}-secrets"
  labels:
    app: "{{ kube_resource_name }}"
type: Opaque
data:
  BUSTERLEAGUE__DEFAULT_SLACK_CHANNEL: {{ busterleague_default_slack_channel | b64encode }}
  BUSTERLEAGUE__EMAIL_BCC_ADDRESS: {{ busterleague_email_bcc_address | b64encode }}
  BUSTERLEAGUE__EMAIL_FROM_ADDRESS: {{ busterleague_email_from_address | b64encode }}
  BUSTERLEAGUE__EMAIL_FROM_NAME: {{ busterleague_email_from_name | b64encode }}
  BUSTERLEAGUE__LOCATION: {{ busterleague_location | b64encode }}
  BUSTERLEAGUE__REDIS_URL: {{ busterleague_redis_url | b64encode }}
  BUSTERLEAGUE__SESSION_TOKEN: {{ busterleague_session_token | b64encode }}
  BUSTERLEAGUE__ROLLBAR_TOKEN: {{ busterleague_rollbar_token | b64encode }}
  BUSTERLEAGUE__SLACK_WEBHOOK: {{ busterleague_slack_webhook | b64encode }}
  BUSTERLEAGUE__UPLOAD_HASH_KEY: {{ busterleague_upload_hash_key | b64encode }}
  BUSTERLEAGUE__URLWRITER_HOST: {{ busterleague_urlwriter_host | b64encode }}
  BUSTERLEAGUE__WEB_REPORTS_BASE_URL: {{ busterleague_web_reports_base_url | b64encode }}
  DATABASE_HOST: {{ database_host | b64encode }}
  DATABASE_NAME: {{ database_name | b64encode }}
  DATABASE_USER: {{ database_user |  b64encode }}
  DATABASE_PASSWORD: {{ database_password | b64encode }}
  DATABASE_POOL_SIZE: {{ database_pool_size | b64encode }}
  DATABASE_PORT: {{ database_port |  b64encode }}
  SMTP_RELAY_HOST: {{ smtp_relay_host |  b64encode }}
  SMTP_PORT: {{ smtp_port |  b64encode }}
