# === COPYRIGHT:
# Copyright (c) Jason Adam Young
# === LICENSE:
# see LICENSE file

class StatTools

  BATTING_STAT_HEADERS = {
      "name" => {cast: 'string'},
      "flag" => {cast: 'string'},
      "team" => {cast: 'string'},
      "p" => {cast: 'string'},
      "age" => {cast: 'integer'},
      "avg" => {cast: 'float'},        
      "obp" => {cast: 'float'},      
      "spc" => {cast: 'float'},      
      "ab" => {cast: 'integer'},
      "h" => {cast: 'integer'},
      "2b" => {cast: 'integer'},
      "3b" => {cast: 'integer'},
      "hr" => {cast: 'integer'},
      "r" => {cast: 'integer'},
      "rbi" => {cast: 'integer'},
      "hbp" => {cast: 'integer'},
      "bb" => {cast: 'integer'},
      "k" => {cast: 'integer'},
      "sb" => {cast: 'integer'},
      "cs" => {cast: 'integer'},
      "gs" => {cast: 'integer'},
      "pa" => {cast: 'integer'},
      "sh" => {cast: 'integer'},
      "sf" => {cast: 'integer'},
      "gdp" => {cast: 'integer'},
      "ops" => {cast: 'float'},      
      "rc" => {cast: 'float'},      
      "rc27" => {cast: 'float'},      
      "iso" => {cast: 'float'},      
      "tavg" => {cast: 'float'},      
      "sec" => {cast: 'float'},      
      "ebh" => {cast: 'integer'},
      "tb" => {cast: 'integer'},
      "pa_per_g" => {cast: 'float'},      
      "ab_per_g" => {cast: 'float'},      
      "bip" => {cast: 'integer'},
      "ipavg" => {cast: 'float'},      
      "tbw" => {cast: 'integer'},
      "tbw_per_pa" => {cast: 'float'},      
      "tbwh" => {cast: 'integer'},
      "tbwh_per_pa" => {cast: 'float'},      
      "k_per_bb" => {cast: 'float'},      
      "l_avg" => {cast: 'float'},      
      "l_obp" => {cast: 'float'},      
      "l_spc" => {cast: 'float'},      
      "l_ops" => {cast: 'float'},      
      "l_ab" => {cast: 'integer'},
      "l_h" => {cast: 'integer'},
      "l_2b" => {cast: 'integer'},
      "l_3b" => {cast: 'integer'},
      "l_hr" => {cast: 'integer'},
      "l_rbi" => {cast: 'integer'},
      "l_bb" => {cast: 'integer'},
      "l_k" => {cast: 'integer'},
      "r_avg"  => {cast: 'float'},             
      "r_obp" => {cast: 'float'},      
      "r_spc" => {cast: 'float'},      
      "r_ops" => {cast: 'float'},      
      "r_ab" => {cast: 'integer'},
      "r_h" => {cast: 'integer'},
      "r_2b" => {cast: 'integer'},
      "r_3b" => {cast: 'integer'},
      "r_hr" => {cast: 'integer'},
      "r_rbi" => {cast: 'integer'},
      "r_bb" => {cast: 'integer'},
      "r_k" => {cast: 'integer'}
  }



end