development:
  adapter: redis
  url: <%= ENV.fetch("BUSTERLEAGUE__REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: busterleague_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("BUSTERLEAGUE__REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: busterleague_production
