default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DATABASE_POOL_SIZE") { 5 } %>
  database: <%= ENV.fetch("DATABASE_NAME") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>
  sslmode: <%= ENV.fetch("DATABASE_SSLMODE") %>
  sslrootcert: <%= Rails.root.join('config', ENV.fetch("DATABASE_SSLROOTCERT") ) %>


development:
  <<: *default
  reconnect: false

production:
  <<: *default
